# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
checkoutLocation: redwood
workspaceLocation: .

tasks:
  - name: Terminal
    openMode: split-left
    before: |
      export RWFW_PATH="/workspace/redwood"
      export RWJS_DEV_API_URL="http://localhost"
    init: |
      mkdir /workspace/rw-test-app
    command: |
      cd /workspace/rw-test-app
      echo -e "\n\n\033[94m ======================================================" && echo -e "\n\033[33m ⌛ Please wait until the dev server is running on the right-side terminal. \n "rw-test-app" is being generated & linked with latest framework code. \n\nIf you make further changes to the framework..." &&  echo -e "1. \033[33mEnsure env vars are set \033[92m'export RWFW_PATH="/workspace/redwood" RWJS_DEV_API_URL="http://localhost"'\033[33m" && echo -e "2. \033[33mRun \033[92m'yarn rwfw project:sync'\033[33m to watch & sync changes into the test project" &&  echo -e "\n\033[94m ======================================================\n\n"


  - name: "Dev Servers"
    openMode: split-right
    before: |
      export RWFW_PATH="/workspace/redwood"
      export RWJS_DEV_API_URL="http://localhost"
      export REDWOOD_DISABLE_TELEMETRY=1
    init: |
      cd /workspace/redwood
      yarn install
      yarn run build:test-project ../rw-test-app --typescript --link --verbose
    command: |
      cd /workspace/rw-test-app
      yarn rw dev


ports:
  - port: 8911
    onOpen: ignore
    visibility: public
  - port: 8910
    onOpen: notify

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
